insert into country (code, name) values ('AD', 'Andorra');
insert into country (code, name) values ('AO', 'Angola');
insert into country (code, name) values ('AI', 'Anguilla');
insert into country (code, name) values ('AQ', 'Antarctica');
insert into country (code, name) values ('AG', 'Antigua and Barbuda');
insert into country (code, name) values ('AR', 'Argentina');
insert into country (code, name) values ('AM', 'Armenia');
insert into country (code, name) values ('AW', 'Aruba');
insert into country (code, name) values ('AU', 'Australia');
insert into country (code, name) values ('AT', 'Austria');
insert into country (code, name) values ('AZ', 'Azerbaijan');
insert into country (code, name) values ('BS', 'Bahamas');
insert into country (code, name) values ('BH', 'Bahrain');
insert into country (code, name) values ('BD', 'Bangladesh');
insert into country (code, name) values ('BB', 'Barbados');
insert into country (code, name) values ('BY', 'Belarus');
insert into country (code, name) values ('BE', 'Belgium');
insert into country (code, name) values ('BZ', 'Belize');
insert into country (code, name) values ('BJ', 'Benin');
insert into country (code, name) values ('BM', 'Bermuda');
insert into country (code, name) values ('BT', 'Bhutan');
insert into country (code, name) values ('BO', 'Bolivia, Plurinational State of');
insert into country (code, name) values ('BQ', 'Bonaire, Sint Eustatius and Saba');
insert into country (code, name) values ('BA', 'Bosnia and Herzegovina');
insert into country (code, name) values ('BW', 'Botswana');
insert into country (code, name) values ('BV', 'Bouvet Island');
insert into country (code, name) values ('BR', 'Brazil');
insert into country (code, name) values ('IO', 'British Indian Ocean Territory');
insert into country (code, name) values ('BN', 'Brunei Darussalam');
insert into country (code, name) values ('BG', 'Bulgaria');
insert into country (code, name) values ('BF', 'Burkina Faso');
insert into country (code, name) values ('BI', 'Burundi');
insert into country (code, name) values ('KH', 'Cambodia');
insert into country (code, name) values ('CM', 'Cameroon');
insert into country (code, name) values ('CA', 'Canada');
insert into country (code, name) values ('CV', 'Cape Verde');
insert into country (code, name) values ('KY', 'Cayman Islands');
